#!/bin/bash

# Clear the screen
clear

# Change to root directory
cd || exit

# Change directory to the code path
cd ./Downloads/project/frea/code || exit

# Activate the virtual environment (if exist)
source ../.venv/bin/activate || exit

# Function to deactivate virtual environment and return to main directory
cleanup() {
    deactivate 2>/dev/null || true
    cd - >/dev/null || true
}

# Trap CTRL+C and call cleanup function
trap cleanup INT

# Execute the Python script
python main.py

# Call cleanup function after Python script exits
cleanup
