#!/bin/bash

# Clear the screen
clear

# Change to the directory where the script is located
SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR" || exit

# Change to the project root directory
cd .. || exit

# Activate the virtual environment (if exist)
source .venv/bin/activate || exit

# Function to deactivate virtual environment and return to main directory
cleanup() {
    deactivate 2>/dev/null || true
    cd - >/dev/null || true
}

# Trap CTRL+C and call cleanup function
trap cleanup INT

# Execute the Python script
python src/main.py

# Call cleanup function after Python script exits
cleanup
